export const STORAGE_KEY_USER = 'STORAGE_KEY_USER';
export const STORAGE_KEY_ACCESS_TOKEN = 'STORAGE_KEY_ACCESS_TOKEN';
export const STORAGE_KEY_REFRESH_TOKEN = 'STORAGE_KEY_REFRESH_TOKEN';
export const STORAGE_KEY_USER_STATUS = 'STORAGE_KEY_USER_STATUS';

export const STORAGE_KEY_SHOW_ONLINE_CLASSES = 'STORAGE_KEY_SHOW_ONLINE_CLASSES';

